# Generated by Django 4.1.4 on 2023-01-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_biography_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
